{% set name = "geodatasets" %}
{% set version = "2023.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9de9c67d31477ab6f06db235e8af2fcc4a7286d48479ce44b96770c3e5746271

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pooch

test:
  imports:
    - geodatasets.data
    - geodatasets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/geopandas/geodatasets
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Spatial data examples
  description: |
    Fetch links or download and cache spatial data example files. The geodatasets
    contains an API on top of a JSON with metadata of externally hosted datasets
    containing geospatial information useful for illustrative and educational purposes.
  doc_url: https://geodatasets.readthedocs.io/
  dev_url: https://github.com/geopandas/geodatasets

extra:
  recipe-maintainers:
    - martinfleis
