{% set name = "geodatasets" %}
{% set version = "2024.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ea1b0f885f1b3305d4a308b2ddee042e425c5288b5ff6b00e6b0ac74a4d5e8d9

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - python >={{ python_min }}
    - pooch

test:
  imports:
    - geodatasets.data
    - geodatasets
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/geopandas/geodatasets
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Spatial data examples
  description: |
    Fetch links or download and cache spatial data example files. The geodatasets
    contains an API on top of a JSON with metadata of externally hosted datasets
    containing geospatial information useful for illustrative and educational purposes.
  doc_url: https://geodatasets.readthedocs.io/
  dev_url: https://github.com/geopandas/geodatasets

extra:
  recipe-maintainers:
    - martinfleis
